# Generated by Django 4.2.10 on 2024-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='current',
            field=models.BooleanField(default=True, help_text='Show in list of current songs'),
        ),
    ]
