# Generated by Django 5.0.3 on 2024-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(choices=[('pdf', 'Pdf'), ('mp3', 'Mp3'), ('other', 'Other')], default='other', max_length=35),
        ),
    ]
