# Generated by Django 5.1 on 2024-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_file_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.TextField(),
        ),
    ]
