# Generated by Django 4.2.15 on 2024-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
