# Generated by Django 5.1 on 2025-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_slug_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embed',
            field=models.TextField(blank=True, help_text='Embed code for the song, e.g., a YouTube link or MuseScore embed'),
        ),
    ]
