# Generated by Django 5.1 on 2025-08-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_details_alter_occurrence_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='description',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, help_text='Internal description, not published', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
