# Generated by Django 5.1 on 2025-08-20 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventtype_description_alter_event_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='closer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closer_occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='opener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opener_occurrences', to=settings.AUTH_USER_MODEL),
        ),
    ]
