# Generated by Django 5.1 on 2025-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_occurrence_closer_occurrence_opener'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
